export type NavItem={key:string;label:string;path:string;icon:string};
export const adminNavigation:NavItem[]=[
 {key:'dashboard',label:'仪表盘',path:'/',icon:'layout-dashboard'},
 {key:'notice',label:'公告管理',path:'/notice',icon:'megaphone'},
 {key:'payment',label:'支付配置',path:'/payment',icon:'credit-card'},
 {key:'knowledge',label:'知识库管理',path:'/knowledge',icon:'book-open'},
 {key:'machine',label:'服务器管理',path:'/server/machine',icon:'server'},
 {key:'node',label:'节点管理',path:'/server/manage',icon:'network'},
 {key:'group',label:'权限组管理',path:'/server/group',icon:'layers-3'},
 {key:'route',label:'路由管理',path:'/server/route',icon:'route'},
 {key:'plan',label:'套餐管理',path:'/finance/plan',icon:'package'},
 {key:'order',label:'订单管理',path:'/finance/order',icon:'shopping-cart'},
 {key:'coupon',label:'优惠券管理',path:'/finance/coupon',icon:'ticket'},
 {key:'gift-card',label:'礼品卡管理',path:'/finance/gift-card',icon:'credit-card'},
 {key:'user',label:'用户管理',path:'/user/manage',icon:'users'},
 {key:'ticket',label:'工单管理',path:'/user/ticket',icon:'messages-square'},
 {key:'config',label:'系统配置',path:'/config',icon:'sliders-horizontal'},
 {key:'mail-template',label:'邮件模板',path:'/mail/template',icon:'mail'},
 {key:'theme',label:'主题配置',path:'/theme',icon:'palette'},
 {key:'plugin',label:'插件管理',path:'/plugin',icon:'puzzle'},
 {key:'system',label:'系统管理',path:'/system',icon:'settings'},
 {key:'traffic-reset',label:'流量重置',path:'/traffic-reset',icon:'refresh-cw'},
];
