import React from 'react';
import * as Icons from 'lucide-react';
import { adminNavigation, dashboardLink } from '../types/navigation';

type Props={path:string;onNavigate:(path:string)=>void;dark:boolean;onToggleDark:()=>void;children:React.ReactNode};
const iconFor=(name:string)=>{const key=name.split('-').map((p,i)=>i?p[0].toUpperCase()+p.slice(1):p).join('');return (Icons as any)[key]??Icons.Circle};
export function AdminShell({path,onNavigate,dark,onToggleDark,children}:Props){
 const [open,setOpen]=React.useState<Record<string,boolean>>(()=>Object.fromEntries(adminNavigation.map(g=>[g.key,true])));
 const active=(p:string)=>p==='/'?path==='/':path===p||path.startsWith(`${p}/`);
 return <div className={dark?'shell dark':'shell'}><aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark">X</div><div><strong>XBoard</strong><span>Admin</span></div></div><nav className="sidebar-nav"><button className={`nav-item ${active('/')?'active':''}`} onClick={()=>onNavigate(dashboardLink.path)}>{React.createElement(iconFor(dashboardLink.icon),{size:17})}<span>{dashboardLink.label}</span></button>{adminNavigation.map(group=>{const GI=iconFor(group.icon);const hasActive=group.items.some(i=>active(i.path));return <div className="nav-group" key={group.key}><button className={`nav-group-head ${hasActive?'group-active':''}`} onClick={()=>setOpen(v=>({...v,[group.key]:!v[group.key]}))}>{React.createElement(GI,{size:17})}<span>{group.label}</span><span className="chevron">{open[group.key]?'▾':'▸'}</span></button>{open[group.key]&&<div className="nav-sub">{group.items.map(item=>{const I=iconFor(item.icon);return <button key={item.key} className={`nav-item sub ${active(item.path)?'active':''}`} onClick={()=>onNavigate(item.path)}>{React.createElement(I,{size:15})}<span>{item.label}</span></button>})}</div>}</div>})}</nav></aside><div className="shell-main"><header className="topbar"><div className="top-search"><Icons.Search size={16}/><span>搜索菜单和功能...</span><kbd>⌘K</kbd></div><div className="top-actions"><button className="icon-btn" onClick={onToggleDark} aria-label="切换深色模式"><Icons.Moon size={18}/></button><button className="lang-btn">🇨🇳 <span>CN</span><Icons.ChevronDown size={14}/></button><button className="avatar-btn">A</button></div></header><main className="page-content">{children}</main></div></div>;
}
